version: '3.1'

services:

 db:
  image: mariadb
  restart: always
  environment:
     MYSQL_ROOT_PASSWORD: 12345
  volumes:
    - /home/vncuser/dockerdir/mysql:/var/lib/mysql

 adminer:
  image: adminer
  restart: always
  ports:
     - 6080:8080
