FROM ubuntu

MAINTAINER xeladock

RUN apt update
RUN apt install -y nginx
RUN apt install -y procps
RUN apt install	-y iproute2
RUN rm -rf /var/kib/apt/lists
ADD nginx.conf /usr/share/nginx/nginx.conf

EXPOSE 80/tcp 443/tcp

CMD ["nginx", "-g", "daemon off;" ]
